Repository mozilla/donate-wagtail, pull requests merged in 2020-07, with the labels that each got.

#1062 Update disclaimer text for the Mozilla donation form
  donate/templates/fragments/donate_form_disclaimer_master.html
  donate/thunderbird/templates/fragments/donate_form_disclaimer.html
Labels: engineering, front-end, ready-to-merge

#1075 slack payload typo
  donate/core/management/commands/review_app_admin.py
Labels: devops

#1074 update to python 3.7.8
  dockerfiles/Dockerfile.python
  runtime.txt
Labels: devops, ready-to-merge, unplanned
