Repository mozilla/donate-wagtail, pull requests merged in 2020-05, with the labels that each got.

#954 Enable debugging in VSCode with ptvsd
  .gitignore
  .vscode/launch.json
  Pipfile
  Pipfile.lock
  README.md
  docker-compose.yml
  env.default
  manage.py
Labels: engineering

#971 add ready to merge label for mergify
  .mergify.yml
Labels: devops, ready-to-merge

#978 update python to 3.7.7
  runtime.txt
Labels: devops, ready-to-merge

#967 Removing pipenv
  .devcontainer/devcontainer.json
  .gitignore
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  dev-requirements.in
  dev-requirements.txt
  docker-compose.yml
  dockerfiles/Dockerfile.node
  dockerfiles/Dockerfile.python
  docs/local_dev.md
  donate/core/management/commands/review_app_admin.py
  env.default
  package.json
  requirements.in
  requirements.txt
  tasks.py
  travis-scripts/python-install.sh
Labels: devops, ready-to-merge

#992 Replacing merge by squash in mergify
  .mergify.yml
Labels: devops, ready-to-merge

#960 Adding a language switcher
  donate/core/templatetags/util_tags.py
  donate/settings/base.py
  donate/settings/languages.py
  donate/templates/fragments/language_switcher.html
  donate/templates/fragments/svg-sprites.html
  donate/templates/pages/base_page_master.html
  donate/urls.py
  source/sass/components/_footer-custom-select.scss
  source/sass/components/_footer-links.scss
  source/sass/components/_footer.scss
  source/sass/main.scss
Labels: ready-to-merge

#997 Downgrade postcss-cli to a version compatible with node 8
  package-lock.json
  package.json
Labels: devops, ready-to-merge
